#!/bin/bash
# MyClaude TLS/SSL Certificate Generator
# Creates self-signed certificates for local LAN/production use

set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
CERT_DIR="/etc/ssl/myclaude"
NGINX_CONF="/etc/nginx/sites-enabled/myclaude"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Get local IP addresses
get_local_ips() {
    hostname -I | tr ' ' '\n' | grep -E '^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)' | head -5
}

# Generate self-signed certificate
generate_cert() {
    local domain="${1:-localhost}"
    local ips=()

    # Collect IPs
    while IFS= read -r ip; do
        [ -n "$ip" ] && ips+=("IP:$ip")
    done < <(get_local_ips)

    # Always include localhost
    ips+=("IP:127.0.0.1" "IP:::1")

    # Add custom domain if provided
    if [ "$domain" != "localhost" ]; then
        ips+=("DNS:$domain")
    fi

    local san_list=$(IFS=,; echo "${ips[*]}")

    log_info "Generating TLS certificate for: $domain"
    log_info "Subject Alternative Names: $san_list"

    # Create cert directory
    sudo mkdir -p "$CERT_DIR"
    sudo chown root:root "$CERT_DIR"
    sudo chmod 755 "$CERT_DIR"

    # Generate private key
    sudo openssl genrsa -out "$CERT_DIR/myclaude.key" 2048 2>/dev/null
    sudo chmod 600 "$CERT_DIR/myclaude.key"

    # Generate certificate with SAN
    sudo openssl req -new -x509 -key "$CERT_DIR/myclaude.key" \
        -out "$CERT_DIR/myclaude.crt" \
        -days 825 \
        -subj "/CN=MyClaude Local Proxy" \
        -addext "subjectAltName=$san_list" \
        2>/dev/null

    sudo chmod 644 "$CERT_DIR/myclaude.crt"

    log_success "Certificate generated at $CERT_DIR/"
    log_info "  Certificate: $CERT_DIR/myclaude.crt"
    log_info "  Private Key: $CERT_DIR/myclaude.key"
}

# Update nginx config for HTTPS
update_nginx_https() {
    local domain="${1:-localhost}"
    local enable_http="${2:-true}"

    log_info "Updating nginx configuration for HTTPS..."

    # Backup original
    sudo cp "$NGINX_CONF" "${NGINX_CONF}.bak.$(date +%s)"

    # Create new HTTPS config (based on nginx-myclaude.conf template)
    sudo tee "$NGINX_CONF" > /dev/null <<NGINXEOF
# MyClaude nginx reverse proxy with TLS
# Generated by setup-tls.sh on $(date)

upstream litellm_backend {
    server 127.0.0.1:4001 max_fails=3 fail_timeout=30s;
    keepalive 32;
    keepalive_requests 1000;
    keepalive_timeout 60s;
}

# HTTP server (redirects to HTTPS if enabled)
server {
    listen 4000;
    listen [::]:4000;
    server_name $domain;

    # Security headers
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Request/response size limits (on-demand optimized)
    client_max_body_size 50M;
    client_body_buffer_size 64k;
    client_header_buffer_size 512;
    large_client_header_buffers 4 8k;

    # Timeouts
    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 3600s;

    # Rate limiting
    limit_req zone=myclaude burst=32 nodelay;
    limit_req_status 503;
    limit_req_log_level warn;

$(if [ "$enable_http" = "true" ]; then cat <<'HTTPEOF'
    location / {
        limit_req zone=myclaude burst=32 nodelay;
        limit_req_status 503;
        limit_req_log_level warn;

        proxy_pass http://litellm_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "";

        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;

        proxy_buffering off;
        proxy_request_buffering off;

        proxy_pass_header Server;
        proxy_pass_header Date;
        proxy_hide_header X-Powered-By;
    }
HTTPEOF
else cat <<'HTTPSEOF'
    location / {
        return 301 https://\$host:4443\$request_uri;
    }
HTTPSEOF
)}

    location = /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
        add_header Cache-Control "no-store";
    }

    location = /health/litellm {
        access_log off;
        proxy_pass http://litellm_backend/health;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }

    location = /metrics {
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
        proxy_pass http://litellm_backend/metrics;
    }

    location ~ ^/(admin|config|models|keys) {
        deny all;
        return 404;
    }
}

# HTTPS server (port 4443)
server {
    listen 4443 ssl http2;
    listen [::]:4443 ssl http2;
    server_name $domain;

    ssl_certificate $CERT_DIR/myclaude.crt;
    ssl_certificate_key $CERT_DIR/myclaude.key;

    # Modern SSL config
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout 5s;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    client_max_body_size 50M;
    client_body_buffer_size 64k;
    client_header_buffer_size 512;
    large_client_header_buffers 4 8k;

    client_body_timeout 60s;
    client_header_timeout 60s;
    send_timeout 3600s;

    # Rate limiting
    limit_req zone=myclaude burst=32 nodelay;
    limit_req_status 503;
    limit_req_log_level warn;

    location / {
        proxy_pass http://litellm_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "";

        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;

        proxy_buffering off;
        proxy_request_buffering off;

        proxy_pass_header Server;
        proxy_pass_header Date;
        proxy_hide_header X-Powered-By;
    }

    location = /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    location = /health/litellm {
        access_log off;
        proxy_pass http://litellm_backend/health;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }

    location = /metrics {
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;
        proxy_pass http://litellm_backend/metrics;
    }

    location ~ ^/(admin|config|models|keys) {
        deny all;
        return 404;
    }
}
NGINXEOF

    log_success "Nginx configuration updated"
}

# Test nginx config and reload
test_and_reload_nginx() {
    log_info "Testing nginx configuration..."
    if sudo nginx -t 2>&1 | grep -q "successful"; then
        sudo systemctl reload nginx
        log_success "Nginx reloaded successfully"
    else
        log_error "Nginx configuration test failed!"
        sudo nginx -t
        exit 1
    fi
}

# Show connection info
show_connection_info() {
    local domain="${1:-localhost}"
    local enable_http="${2:-true}"

    echo ""
    log_success "=== TLS Setup Complete ==="
    echo ""
    echo "Certificate: $CERT_DIR/myclaude.crt"
    echo "Private Key: $CERT_DIR/myclaude.key"
    echo ""
    echo "To use from clients:"
    echo ""

    # Get IPs for display
    local ips=()
    while IFS= read -r ip; do
        [ -n "$ip" ] && ips+=("$ip")
    done < <(get_local_ips)

    if [ "$enable_http" = "true" ]; then
        echo "HTTP (port 4000):"
        for ip in "${ips[@]}"; do
            echo "  export ANTHROPIC_BASE_URL=\"http://$ip:4000\""
        done
        echo "  export ANTHROPIC_API_KEY=\"sk-local-proxy-key\""
        echo ""
    fi

    echo "HTTPS (port 4443) - REQUIRES TRUSTING SELF-SIGNED CERT:"
    for ip in "${ips[@]}"; do
        echo "  export ANTHROPIC_BASE_URL=\"https://$ip:4443\""
    done
    echo "  export ANTHROPIC_API_KEY=\"sk-local-proxy-key\""
    echo ""
    echo "  # For curl, use -k to skip cert verification:"
    echo "  curl -k https://<ip>:4443/health"
    echo ""
    echo "  # For Claude Code, you may need to trust the cert system-wide:"
    echo "  sudo cp $CERT_DIR/myclaude.crt /usr/local/share/ca-certificates/myclaude.crt"
    echo "  sudo update-ca-certificates"
    echo ""
}

# Disable TLS (restore HTTP-only)
disable_tls() {
    log_info "Disabling TLS, restoring HTTP-only configuration..."

    # Copy the HTTP-only template from nginx-myclaude.conf
    if [ -f "$REPO_DIR/nginx-myclaude.conf" ]; then
        sudo cp "$REPO_DIR/nginx-myclaude.conf" "$NGINX_CONF"
    else
        log_error "nginx-myclaude.conf template not found"
        exit 1
    fi

    test_and_reload_nginx
    log_success "TLS disabled, HTTP-only restored on port 4000"
}

# Main
main() {
    case "${1:-generate}" in
        generate)
            local domain="${2:-localhost}"
            local enable_http="${3:-true}"
            generate_cert "$domain"
            update_nginx_https "$domain" "$enable_http"
            test_and_reload_nginx
            show_connection_info "$domain" "$enable_http"
            ;;
        disable)
            disable_tls
            ;;
        info)
            show_connection_info "localhost" "true"
            ;;
        *)
            echo "Usage: $0 [generate|disable|info] [domain] [enable_http]"
            echo "  generate [domain] [true|false]  - Generate certs and enable HTTPS (default)"
            echo "  disable                         - Disable HTTPS, restore HTTP-only"
            echo "  info                            - Show connection info"
            exit 1
            ;;
    esac
}

main "$@"